/* Generated by automated build script */
#define SNAPSHOT
#define TEXTVER "Development snapshot 2014-10-02.r10281"
#define SSHVER "PuTTY-Snapshot-2014-10-02.r10281"
#define BINARY_VERSION 0,63,10345,0
